### PR TITLE
Use PostGIS from official Docker repo

### PR DESCRIPTION
**Pull request by dimaqq**
- [x] use `postgis/postgis` instead of `mdillon/postgis`
- [x] use PostGres 14 (14.2 I hope?)
- [x] use newest PostGIS (3.2)
- [ ] not sure if e.g. data path needs to be updated

### CODE REVIEW

**Review by Dale-Koenig — APPROVED** [review]
Probably need to also change a bunch of docker compose files, maybe good idea to just ctrl-shift-f for the old postgis

**Comment by dimaqq** [comment]
> Probably need to also change a bunch of docker compose files, maybe good idea to just ctrl-shift-f for the old postgis

Done, linked above☝🏿

**Comment by larryng-rapyuta** [comment]
@dimaqq I think the workflow for those changes were supposed to be by changing the packages on the io-amr project in rapyuta.io and then we can run the git action that will update this repo by pulling the latest packages from there. Otherwise the packages on io-amr will be different than the ones here cc @Vuwij

**Comment by dimaqq** [comment]
@Vuwij is on vacation until next week. I suppose this can wait 🤔

**Comment by dimaqq** [comment]
This will be done in #94, closing.

**Pull request closed without merging**
