### PR TITLE
updated images, reverted deployment networks to use melodic, updated README and …

### PR DESCRIPTION
**Pull request by larryng-rapyuta**
…added variable checking of certain variables (docker user/pass and prefix name)

### CODE REVIEW

**Review by yuokamoto — APPROVED** [review]
lgtm
confirmd deployment works

**Review by dhananjaysathe — APPROVED** [review]

**Comment by dhananjaysathe** [comment]
Can we include latest ansible it supports noetic ; why was revert to melodic , tbh it does not really matter but wanted to understand the rational

**Comment by larryng-rapyuta** [comment]
I was originally getting some errors with noetic since as I now know my system didn't run the latest ansible modules. but now I've tested and updated it, but haven't pushed reverting the networks to use noetic yet as I was looking into another issue Tadanori-san found where I confirmed that using a new previously unused prefix seems to sometimes end up with a state where the amrs dont spawn

**Comment by larryng-rapyuta** [comment]
Found that the occasional instances where the AMRs do not spawn appears to be related to the deployments being deployed asynchronously, as such since it helps with debugging as well, I've set it up such that running the playbook asynchronously can be turned off with ansible_async = false in the configs. This should provide a secondary stable method of deploying at the cost of speed.

**Pull request merged**
